# Generated by Django 4.2.7 on 2024-10-15 19:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('date_applied', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Withdrawn', 'Withdrawn')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_details_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
